#!/bin/sh

# PROVIDE: minecraft_check_empty
# REQUIRE: LOGIN DAEMON NETWORKING
# KEYWORD: minecraft

# Enable this script by adding:
# minecraft_check_empty_enable="YES"
# ... to /etc/rc.conf
rc_debug=yes

. /etc/rc.subr
name=minecraft_check_empty

rcvar=minecraft_check_empty_enable
load_rc_config ${name}

: ${minecraft_check_empty_user:=rintse}
: ${minecraft_check_empty_group:=rintse}

# This is the tool init launches
command="/usr/sbin/daemon"

pidfile="/var/run/${name}/${name}.pid"

task="/usr/local/bin/${name}"
procname="${task}"

command_args="-p ${pidfile} -T ${name} ${task}"

start_precmd="start_precmd"
start_precmd()
{
    if [ ! -e "/var/run/${name}" ] ; then
        install -d -o ${minecraft_check_empty_user} -g ${minecraft_check_empty_group} /var/run/${name};
    fi
}

run_rc_command "$1"
